module.exports = {
  "order-ready": "ORDER READY",
  "package-comes-to-end": "PACAKGE COMES TO END",
  "verify-material": "VERIFY MATERIAL",
  "raw-material-reached": "Raw MATERIAL REACHED",
  "raw-material-ordered": "RAW MATERIAL ORDERED",
  "edit-order": "EDIT ORDER",
  "worker-multiple": "WORKER ARRIEVED",
  "worker-single": "WORKER ARRIEVED",
  "order-shipped": "ORDER SHIPPED",
  "order-reached": "ORDER REACHED",
  "product-updated": "PRODUCT UPDATED",
  "lane-occupied": "LANE OCCUPIED",
  "lane-empty": "LANE EMPTY",
  "cancel-order": "CANCEL OEDER",
  "production-start": "PRODUCTION START",
  "production-completed": "PRODUCTION COMPLETED",
  "calendar-event-scheduled": "CALENDAR EVENT SCHEDULED",
  "scheduled-date-event": "DATE EVENT SCHEDULED",
};
